version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123

    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: PropertyManagement.Web/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro

volumes:
  mssql_data: