version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 15
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - appnet
    restart: unless-stopped

  web:
    build:
      context: ./PropertyManagement.Web
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PropertyManagementDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=True
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    networks:
      - appnet
    restart: always

volumes:
  mssql_data:

networks:
  appnet:
    driver: bridge