services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 15
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - appnet
    restart: unless-stopped

  web:
    image: ghcr.io/zamahele/tenantmanagement:test
    pull_policy: always
    ports:
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      kibana:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PropertyManagementDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=True
      - Serilog__WriteTo__2__Name=Elasticsearch
      - Serilog__WriteTo__2__Args__NodeUris=http://elasticsearch:9200
    volumes:
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    networks:
      - appnet
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - appnet
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - appnet
    restart: unless-stopped

volumes:
  mssql_data:
  esdata:

networks:
  appnet:
    driver: bridge