apiVersion: v1
kind: Secret
metadata:
  name: sql-server-secret
  namespace: property-management
type: Opaque
data:
  # Base64 encoded: Your_password123
  SA_PASSWORD: WW91cl9wYXNzd29yZDEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: property-management
type: Opaque
data:
  # Base64 encoded: Production
  ASPNETCORE_ENVIRONMENT: UHJvZHVjdGlvbg==