apiVersion: v1
kind: ServiceMonitor
metadata:
  name: property-management-metrics
  namespace: property-management
  labels:
    app: property-management-web
spec:
  selector:
    matchLabels:
      app: property-management-web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: property-management-hpa
  namespace: property-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: property-management-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60