apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: property-management
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        securityContext:
          runAsUser: 0
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: property-management-secrets
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"
        - name: MSSQL_DATA_DIR
          value: "/var/opt/mssql/data"
        - name: MSSQL_LOG_DIR
          value: "/var/opt/mssql/log"
        - name: MSSQL_BACKUP_DIR
          value: "/var/opt/mssql/backup"
        volumeMounts:
        - name: sql-server-data
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: sql-server-data
        persistentVolumeClaim:
          claimName: sql-server-pvc