name: .NET 8 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        $repoParts = "${{ github.repository }}".ToLower().Split('/')
        $owner = $repoParts[0]
        $repo = if ($repoParts.Length -gt 1) { $repoParts[1] } else { "" }
        if ([string]::IsNullOrEmpty($repo)) {
          Write-Error "Repository name is empty. github.repository='${{ github.repository }}'"
          exit 1
        }
        docker build -t ghcr.io/$owner/$repo:latest .
      shell: pwsh

    - name: Push Docker image
      run: |
        $repoParts = "${{ github.repository }}".ToLower().Split('/')
        $owner = $repoParts[0]
        $repo = $repoParts[1]
        docker push ghcr.io/$owner/$repo:latest
      shell: pwsh

    - name: Debug repo variables
      run: |
        $repoParts = "${{ github.repository }}".ToLower().Split('/')
        Write-Host "repoParts[0]: $($repoParts[0])"
        Write-Host "repoParts[1]: $($repoParts[1])"
      shell: pwsh