name: .NET 8 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Check if Dockerfile exists
    - name: Check for Dockerfile
      run: |
        if (!(Test-Path -Path "./Dockerfile")) {
          Write-Error "Dockerfile not found in repository root."
          exit 1
        }
      shell: pwsh

    - name: Build Docker image
      run: |
        $repoParts = "${{ github.repository }}".ToLower().Trim().Split('/')
        if ($repoParts.Length -ne 2) {
          Write-Error "Unexpected repository format: '${{ github.repository }}'"
          exit 1
        }
        $owner = $repoParts[0]
        $repo = $repoParts[1]
        docker build -t ghcr.io/$owner/$repo:latest .
      shell: pwsh

    - name: Push Docker image
      run: |
        $repoParts = "${{ github.repository }}".ToLower().Trim().Split('/')
        if ($repoParts.Length -ne 2) {
          Write-Error "Unexpected repository format: '${{ github.repository }}'"
          exit 1
        }
        $owner = $repoParts[0]
        $repo = $repoParts[1]
        docker push ghcr.io/$owner/$repo:latest
      shell: pwsh