name: PropertyManagement Build .NET 8

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test with coverage
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

    - name: Upload docker-compose file
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose
        path: docker-compose.yml

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      run: |
        docker build -f ./PropertyManagement.Web/Dockerfile -t ghcr.io/zamahele/tenantmanagement:test .
        docker push ghcr.io/zamahele/tenantmanagement:test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./PropertyManagement.Test/TestResults/**/*.cobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}